## Playbook for manage BIG-IP hostname on F5

---
# file bigip_manage_hostname.yml
# ...
- name: Manage BIG-IP hostnames
  hosts: all
  connection: local
  tasks:
  - name: Create Self IP
    bigip_selfip:
      address: "10.1.30.1"
      allow_service: 
        - "default"
      name: "self_ansible2"
      netmask: "255.255.255.0"
      password: "admin"
      server: "{{ inventory_hostname }}"
      user: "admin"
      validate_certs: "False"
      vlan: "internal"
    register: kp
    delegate_to: localhost
    
  - name: "Debug result"
    debug: var=kp
  
  
