## Playbook for Collect interface and vlan on F5

---
# file test.yml
# ...
- hosts: all
  connection: local
  tasks:
  - name: Collect BIG-IP facts
    bigip_facts:
      server: "{{ inventory_hostname }}"
      user: "admin"
      password: "admin"
      include: "interface,vlan"
      validate_certs: "false"
    register: kp
    delegate_to: localhost
    
  - name: "Debug result"
    debug: var=kp
