## Playbook for Collect info on F5 (Prepared by Frankie Cheung)

---
# file f5_bigip_fact.yml
# ...
- hosts: all
  connection: local
  tasks:
  - name: Get all of the facts from my BIG-IP
    bigip_facts:
        server: "{{ inventory_hostname }}"
        user: "admin"
        password: "admin"
        include: "system_info"
        validate_certs: "false"
    register: kp
    delegate_to: localhost
    
  - name: "Debug result"
    debug: var=kp.stdout
