- name: Hello World Sample
  hosts: {{ inventory_hostname }}
  vars:
    cli:
      username: admin
      password: M@croview1
      transport: cli
  
  tasks:
    - name: run show version on remote devices
      iosxr_command:
        commands: show version
        provider: {{ cli }}
