- name: Hello World Sample
  hosts: all
  gather_facts: False
  connection: local

  vars:
    cli:
    host: "{{ inventory_hostname }}"
      username: admin
      password: M@croview1
      transport: cli

  tasks:
    - name: run show version on remote devices
      ios_command:
        commands: show version
        provider: "{{ cli }}"
