- name: Hello World Sample
  hosts: all
  vars:
    cli:
      username: admin
      password: M@croview1
      transport: cli
  
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

